version: '3'
services:
  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "8880:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - .:/var/www
    depends_on:
      - nodejs
  nodejs:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
  mongo:
    restart: always
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mydatabase
    command: --bind_ip 0.0.0.0